#!/usr/bin/env python3
"""Emit MySQL 8 stored procedure to RENAME COLUMN camelCase -> snake_case on account.

Source of truth: tools/pass4_account_rename.py RENAME map.
Run: python3 tools/migrations/build_pass4_account_mysql.py > tools/migrations/pass4_account_rename_mysql8.sql

Requires MySQL 8.0.2+ (RENAME COLUMN). Backup database first.
"""

import importlib.util
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SPEC = importlib.util.spec_from_file_location("p4", ROOT / "tools" / "pass4_account_rename.py")
MOD = importlib.util.module_from_spec(SPEC)
SPEC.loader.exec_module(MOD)
RENAME: dict[str, str] = MOD.RENAME


def main() -> None:
    unions = " UNION ALL\n    ".join(
        f"SELECT '{old}' AS old_name, '{new}' AS new_name" for old, new in sorted(RENAME.items())
    )
    sql = f"""-- Pass 4: Align MySQL table `account` column names with Espo entityDefs (snake_case).
-- Generated by tools/migrations/build_pass4_account_mysql.py — do not hand-edit; regenerate.
--
-- Prerequisites: MySQL 8.0.2+ (supports RENAME COLUMN).
-- Before running: mysqldump or snapshot; test on a copy.
--
-- Usage (replace db/user):
--   mysql -u root -p your_database < tools/migrations/pass4_account_rename_mysql8.sql
--
-- Idempotent: renames only when old column exists and new column does not.
--
-- If `php command.php rebuild` fails with "Row size too large", that is separate from renames:
-- reduce VARCHAR sizes, move large fields to TEXT, or adjust InnoDB row format (DBA).

DELIMITER $$

DROP PROCEDURE IF EXISTS esp_pass4_rename_account_columns$$

CREATE PROCEDURE esp_pass4_rename_account_columns()
BEGIN
    DECLARE done INT DEFAULT FALSE;
    DECLARE v_old VARCHAR(64);
    DECLARE v_new VARCHAR(64);
    DECLARE v_o INT;
    DECLARE v_n INT;
    DECLARE cur CURSOR FOR
    {unions};
    DECLARE CONTINUE HANDLER FOR NOT FOUND SET done = TRUE;

    OPEN cur;
    read_loop: LOOP
        FETCH cur INTO v_old, v_new;
        IF done THEN
            LEAVE read_loop;
        END IF;

        SELECT COUNT(*) INTO v_o
        FROM information_schema.COLUMNS
        WHERE TABLE_SCHEMA = DATABASE()
          AND TABLE_NAME = 'account'
          AND COLUMN_NAME = v_old;

        SELECT COUNT(*) INTO v_n
        FROM information_schema.COLUMNS
        WHERE TABLE_SCHEMA = DATABASE()
          AND TABLE_NAME = 'account'
          AND COLUMN_NAME = v_new;

        IF v_o > 0 AND v_n = 0 THEN
            SET @esp_sql = CONCAT(
                'ALTER TABLE `account` RENAME COLUMN `',
                v_old,
                '` TO `',
                v_new,
                '`'
            );
            PREPARE esp_stmt FROM @esp_sql;
            EXECUTE esp_stmt;
            DEALLOCATE PREPARE esp_stmt;
        END IF;
    END LOOP;

    CLOSE cur;
END$$

DELIMITER ;

CALL esp_pass4_rename_account_columns();
DROP PROCEDURE IF EXISTS esp_pass4_rename_account_columns;
"""
    sys.stdout.write(sql)


if __name__ == "__main__":
    main()
