-- Pass 4: Align MySQL table `account` column names with Espo entityDefs (snake_case).
-- Generated by tools/migrations/build_pass4_account_mysql.py — do not hand-edit; regenerate.
--
-- Prerequisites: MySQL 8.0.2+ (supports RENAME COLUMN).
-- Before running: mysqldump or snapshot; test on a copy.
--
-- Usage (replace db/user):
--   mysql -u root -p your_database < tools/migrations/pass4_account_rename_mysql8.sql
--
-- Idempotent: renames only when old column exists and new column does not.
--
-- If `php command.php rebuild` fails with "Row size too large", that is separate from renames:
-- reduce VARCHAR sizes, move large fields to TEXT, or adjust InnoDB row format (DBA).

DELIMITER $$

DROP PROCEDURE IF EXISTS esp_pass4_rename_account_columns$$

CREATE PROCEDURE esp_pass4_rename_account_columns()
BEGIN
    DECLARE done INT DEFAULT FALSE;
    DECLARE v_old VARCHAR(64);
    DECLARE v_new VARCHAR(64);
    DECLARE v_o INT;
    DECLARE v_n INT;
    DECLARE cur CURSOR FOR
    SELECT 'accountScore' AS old_name, 'account_score' AS new_name UNION ALL
    SELECT 'accountStatus' AS old_name, 'account_status' AS new_name UNION ALL
    SELECT 'accountType' AS old_name, 'account_type' AS new_name UNION ALL
    SELECT 'agentOfAgencyCode' AS old_name, 'agent_of_agency_code' AS new_name UNION ALL
    SELECT 'agentOfRecordDate' AS old_name, 'agent_of_record_date' AS new_name UNION ALL
    SELECT 'aiAssessment' AS old_name, 'ai_assessment' AS new_name UNION ALL
    SELECT 'annualPremium' AS old_name, 'annual_premium' AS new_name UNION ALL
    SELECT 'annualRevenue' AS old_name, 'annual_revenue' AS new_name UNION ALL
    SELECT 'assessmentDate' AS old_name, 'assessment_date' AS new_name UNION ALL
    SELECT 'bbbRating' AS old_name, 'bbb_rating' AS new_name UNION ALL
    SELECT 'bestTimeToCall' AS old_name, 'best_time_to_call' AS new_name UNION ALL
    SELECT 'carrierCode' AS old_name, 'carrier_code' AS new_name UNION ALL
    SELECT 'claimsCount3yr' AS old_name, 'claims_count_3yr' AS new_name UNION ALL
    SELECT 'claimsCountLifetime' AS old_name, 'claims_count_lifetime' AS new_name UNION ALL
    SELECT 'claimsNotes' AS old_name, 'claims_notes' AS new_name UNION ALL
    SELECT 'claimsOpen' AS old_name, 'claims_open' AS new_name UNION ALL
    SELECT 'clientSince' AS old_name, 'client_since' AS new_name UNION ALL
    SELECT 'communicationNotes' AS old_name, 'communication_notes' AS new_name UNION ALL
    SELECT 'coverageGaps' AS old_name, 'coverage_gaps' AS new_name UNION ALL
    SELECT 'daysToRenewal' AS old_name, 'days_to_renewal' AS new_name UNION ALL
    SELECT 'doNotContact' AS old_name, 'do_not_contact' AS new_name UNION ALL
    SELECT 'driverCount' AS old_name, 'driver_count' AS new_name UNION ALL
    SELECT 'employeeCount' AS old_name, 'employee_count' AS new_name UNION ALL
    SELECT 'estimatedPremium' AS old_name, 'estimated_premium' AS new_name UNION ALL
    SELECT 'estimatedRevenue' AS old_name, 'estimated_revenue' AS new_name UNION ALL
    SELECT 'googleDriveFolderUrl' AS old_name, 'google_drive_folder_url' AS new_name UNION ALL
    SELECT 'insightObjection' AS old_name, 'insight_objection' AS new_name UNION ALL
    SELECT 'insightOpener' AS old_name, 'insight_opener' AS new_name UNION ALL
    SELECT 'insightRelationship' AS old_name, 'insight_relationship' AS new_name UNION ALL
    SELECT 'insightSignal' AS old_name, 'insight_signal' AS new_name UNION ALL
    SELECT 'intelAiSummary' AS old_name, 'intel_ai_summary' AS new_name UNION ALL
    SELECT 'intelAnnualRevenueEst' AS old_name, 'intel_annual_revenue_est' AS new_name UNION ALL
    SELECT 'intelBbbAccredited' AS old_name, 'intel_bbb_accredited' AS new_name UNION ALL
    SELECT 'intelBbbComplaints' AS old_name, 'intel_bbb_complaints' AS new_name UNION ALL
    SELECT 'intelBbbNotes' AS old_name, 'intel_bbb_notes' AS new_name UNION ALL
    SELECT 'intelBbbRating' AS old_name, 'intel_bbb_rating' AS new_name UNION ALL
    SELECT 'intelCargoType' AS old_name, 'intel_cargo_type' AS new_name UNION ALL
    SELECT 'intelConfidence' AS old_name, 'intel_confidence' AS new_name UNION ALL
    SELECT 'intelCrossSell' AS old_name, 'intel_cross_sell' AS new_name UNION ALL
    SELECT 'intelDba' AS old_name, 'intel_dba' AS new_name UNION ALL
    SELECT 'intelDotIncidents' AS old_name, 'intel_dot_incidents' AS new_name UNION ALL
    SELECT 'intelEmployeeCount' AS old_name, 'intel_employee_count' AS new_name UNION ALL
    SELECT 'intelEntityType' AS old_name, 'intel_entity_type' AS new_name UNION ALL
    SELECT 'intelFleetSize' AS old_name, 'intel_fleet_size' AS new_name UNION ALL
    SELECT 'intelGrowthIndicator' AS old_name, 'intel_growth_indicator' AS new_name UNION ALL
    SELECT 'intelLegalName' AS old_name, 'intel_legal_name' AS new_name UNION ALL
    SELECT 'intelLinkedinNotes' AS old_name, 'intel_linkedin_notes' AS new_name UNION ALL
    SELECT 'intelLinkedinUrl' AS old_name, 'intel_linkedin_url' AS new_name UNION ALL
    SELECT 'intelNaics' AS old_name, 'intel_naics' AS new_name UNION ALL
    SELECT 'intelNewsNotes' AS old_name, 'intel_news_notes' AS new_name UNION ALL
    SELECT 'intelOperatingRadius' AS old_name, 'intel_operating_radius' AS new_name UNION ALL
    SELECT 'intelOshaViolations' AS old_name, 'intel_osha_violations' AS new_name UNION ALL
    SELECT 'intelOwnerOperators' AS old_name, 'intel_owner_operators' AS new_name UNION ALL
    SELECT 'intelPackLastRun' AS old_name, 'intel_pack_last_run' AS new_name UNION ALL
    SELECT 'intelPackRun' AS old_name, 'intel_pack_run' AS new_name UNION ALL
    SELECT 'intelPainPoints' AS old_name, 'intel_pain_points' AS new_name UNION ALL
    SELECT 'intelRun' AS old_name, 'intel_run' AS new_name UNION ALL
    SELECT 'intelRunBy' AS old_name, 'intel_run_by' AS new_name UNION ALL
    SELECT 'intelRunDate' AS old_name, 'intel_run_date' AS new_name UNION ALL
    SELECT 'intelSic' AS old_name, 'intel_sic' AS new_name UNION ALL
    SELECT 'intelSignalLinkedin' AS old_name, 'intel_signal_linkedin' AS new_name UNION ALL
    SELECT 'intelSignalNews' AS old_name, 'intel_signal_news' AS new_name UNION ALL
    SELECT 'intelSources' AS old_name, 'intel_sources' AS new_name UNION ALL
    SELECT 'intelSourcesHit' AS old_name, 'intel_sources_hit' AS new_name UNION ALL
    SELECT 'intelUnderwritingFlag' AS old_name, 'intel_underwriting_flag' AS new_name UNION ALL
    SELECT 'intelWebsite' AS old_name, 'intel_website' AS new_name UNION ALL
    SELECT 'intelWebsiteNotes' AS old_name, 'intel_website_notes' AS new_name UNION ALL
    SELECT 'intelYearsInBusiness' AS old_name, 'intel_years_in_business' AS new_name UNION ALL
    SELECT 'keyFindings' AS old_name, 'key_findings' AS new_name UNION ALL
    SELECT 'lastClaimDate' AS old_name, 'last_claim_date' AS new_name UNION ALL
    SELECT 'lastClaimLob' AS old_name, 'last_claim_lob' AS new_name UNION ALL
    SELECT 'lastClaimStatus' AS old_name, 'last_claim_status' AS new_name UNION ALL
    SELECT 'lastClaimType' AS old_name, 'last_claim_type' AS new_name UNION ALL
    SELECT 'lastContactDate' AS old_name, 'last_contact_date' AS new_name UNION ALL
    SELECT 'lastContactMethod' AS old_name, 'last_contact_method' AS new_name UNION ALL
    SELECT 'lastContactOutcome' AS old_name, 'last_contact_outcome' AS new_name UNION ALL
    SELECT 'lastContactType' AS old_name, 'last_contact_type' AS new_name UNION ALL
    SELECT 'linkedinUrl' AS old_name, 'linkedin_url' AS new_name UNION ALL
    SELECT 'momentumClientId' AS old_name, 'momentum_client_id' AS new_name UNION ALL
    SELECT 'momentumLastSynced' AS old_name, 'momentum_last_synced' AS new_name UNION ALL
    SELECT 'mvrFlag' AS old_name, 'mvr_flag' AS new_name UNION ALL
    SELECT 'nextRenewalCarrier' AS old_name, 'next_renewal_carrier' AS new_name UNION ALL
    SELECT 'nextRenewalDate' AS old_name, 'next_renewal_date' AS new_name UNION ALL
    SELECT 'nextRenewalLob' AS old_name, 'next_renewal_lob' AS new_name UNION ALL
    SELECT 'nextXDate' AS old_name, 'next_x_date' AS new_name UNION ALL
    SELECT 'nextXDateLob' AS old_name, 'next_x_date_lob' AS new_name UNION ALL
    SELECT 'npsDate' AS old_name, 'nps_date' AS new_name UNION ALL
    SELECT 'npsScore' AS old_name, 'nps_score' AS new_name UNION ALL
    SELECT 'outreachAttemptsCurrent' AS old_name, 'outreach_attempts_current' AS new_name UNION ALL
    SELECT 'preferredContact' AS old_name, 'preferred_contact' AS new_name UNION ALL
    SELECT 'premiumChangeAmount' AS old_name, 'premium_change_amount' AS new_name UNION ALL
    SELECT 'premiumChangePct' AS old_name, 'premium_change_pct' AS new_name UNION ALL
    SELECT 'propertyAddress' AS old_name, 'property_address' AS new_name UNION ALL
    SELECT 'propertyCity' AS old_name, 'property_city' AS new_name UNION ALL
    SELECT 'propertyCount' AS old_name, 'property_count' AS new_name UNION ALL
    SELECT 'propertyState' AS old_name, 'property_state' AS new_name UNION ALL
    SELECT 'propertyZip' AS old_name, 'property_zip' AS new_name UNION ALL
    SELECT 'rateIncreaseFlag' AS old_name, 'rate_increase_flag' AS new_name UNION ALL
    SELECT 'referralName' AS old_name, 'referral_name' AS new_name UNION ALL
    SELECT 'referralSource' AS old_name, 'referral_source' AS new_name UNION ALL
    SELECT 'renewalDate' AS old_name, 'renewal_date' AS new_name UNION ALL
    SELECT 'renewalDecision' AS old_name, 'renewal_decision' AS new_name UNION ALL
    SELECT 'renewalDecisionNotes' AS old_name, 'renewal_decision_notes' AS new_name UNION ALL
    SELECT 'renewalOutreachStage' AS old_name, 'renewal_outreach_stage' AS new_name UNION ALL
    SELECT 'renewalQuoteAmount' AS old_name, 'renewal_quote_amount' AS new_name UNION ALL
    SELECT 'renewalQuoteCarrier' AS old_name, 'renewal_quote_carrier' AS new_name UNION ALL
    SELECT 'renewalQuoteDate' AS old_name, 'renewal_quote_date' AS new_name UNION ALL
    SELECT 'renewalQuoteReceived' AS old_name, 'renewal_quote_received' AS new_name UNION ALL
    SELECT 'rentalPropertyCount' AS old_name, 'rental_property_count' AS new_name UNION ALL
    SELECT 'rentalPropertyFlag' AS old_name, 'rental_property_flag' AS new_name UNION ALL
    SELECT 'rentalPropertyNotes' AS old_name, 'rental_property_notes' AS new_name UNION ALL
    SELECT 'retentionRisk' AS old_name, 'retention_risk' AS new_name UNION ALL
    SELECT 'rideshareDriverFlag' AS old_name, 'rideshare_driver_flag' AS new_name UNION ALL
    SELECT 'riskScore' AS old_name, 'risk_score' AS new_name UNION ALL
    SELECT 'scoreAlertSent' AS old_name, 'score_alert_sent' AS new_name UNION ALL
    SELECT 'scoreBreakdown' AS old_name, 'score_breakdown' AS new_name UNION ALL
    SELECT 'scoreBundleDepth' AS old_name, 'score_bundle_depth' AS new_name UNION ALL
    SELECT 'scoreChangeAmount' AS old_name, 'score_change_amount' AS new_name UNION ALL
    SELECT 'scoreChangeDirection' AS old_name, 'score_change_direction' AS new_name UNION ALL
    SELECT 'scoreClaimsActivity' AS old_name, 'score_claims_activity' AS new_name UNION ALL
    SELECT 'scoreLastCalculated' AS old_name, 'score_last_calculated' AS new_name UNION ALL
    SELECT 'scoreLastContact' AS old_name, 'score_last_contact' AS new_name UNION ALL
    SELECT 'scorePaymentHistory' AS old_name, 'score_payment_history' AS new_name UNION ALL
    SELECT 'scoreTier' AS old_name, 'score_tier' AS new_name UNION ALL
    SELECT 'scoreTotal' AS old_name, 'score_total' AS new_name UNION ALL
    SELECT 'scoreYearsRetained' AS old_name, 'score_years_retained' AS new_name UNION ALL
    SELECT 'sicCode' AS old_name, 'sic_code' AS new_name UNION ALL
    SELECT 'totalActivePremium' AS old_name, 'total_active_premium' AS new_name UNION ALL
    SELECT 'totalCarrierPremium' AS old_name, 'total_carrier_premium' AS new_name UNION ALL
    SELECT 'vehicleCount' AS old_name, 'vehicle_count' AS new_name UNION ALL
    SELECT 'xDate' AS old_name, 'x_date' AS new_name UNION ALL
    SELECT 'yearsInBusiness' AS old_name, 'years_in_business' AS new_name UNION ALL
    SELECT 'youthfulDriverFlag' AS old_name, 'youthful_driver_flag' AS new_name;
    DECLARE CONTINUE HANDLER FOR NOT FOUND SET done = TRUE;

    OPEN cur;
    read_loop: LOOP
        FETCH cur INTO v_old, v_new;
        IF done THEN
            LEAVE read_loop;
        END IF;

        SELECT COUNT(*) INTO v_o
        FROM information_schema.COLUMNS
        WHERE TABLE_SCHEMA = DATABASE()
          AND TABLE_NAME = 'account'
          AND COLUMN_NAME = v_old;

        SELECT COUNT(*) INTO v_n
        FROM information_schema.COLUMNS
        WHERE TABLE_SCHEMA = DATABASE()
          AND TABLE_NAME = 'account'
          AND COLUMN_NAME = v_new;

        IF v_o > 0 AND v_n = 0 THEN
            SET @esp_sql = CONCAT(
                'ALTER TABLE `account` RENAME COLUMN `',
                v_old,
                '` TO `',
                v_new,
                '`'
            );
            PREPARE esp_stmt FROM @esp_sql;
            EXECUTE esp_stmt;
            DEALLOCATE PREPARE esp_stmt;
        END IF;
    END LOOP;

    CLOSE cur;
END$$

DELIMITER ;

CALL esp_pass4_rename_account_columns();
DROP PROCEDURE IF EXISTS esp_pass4_rename_account_columns;
